# For more information: https://laravel.com/docs/sail
version: '3'
services:
  laravel:
    build:
      context: ./
      dockerfile: Dockerfile.prod
      args:
        API_KEY: '${API_KEY}'
        MAPBOX_ACCESS_TOKEN: '${MAPBOX_ACCESS_TOKEN}'
        RADAR_SECRET: '${RADAR_SECRET}'
        MAIL_USERNAME: '${MAIL_USERNAME}'
        MAIL_PASSWORD: '${MAIL_PASSWORD}'
        DB_USERNAME: '${DB_USERNAME}'
        DB_PASSWORD: '${DB_PASSWORD}'
        SEED_NAME: '${SEED_NAME}'
        SEED_EMAIL: '${SEED_EMAIL}'
        SEED_PASSWORD: '${SEED_PASSWORD}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:8080'
    volumes:
      - 'portal-assets:/app/storage'
    depends_on:
      - mysql
      - redis
    networks:
      - sail
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'accessibility_dashboard'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
  portal-assets:
    driver: local
