# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel:
        build:
            context: ./
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:8080'
        environment:
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            APP_ENV: '${APP_ENV:-local}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            DB_HOST: 'mysql'
            DB_PORT: '${FORWARD_DB_PORT:-33060}'
            DB_DATABASE: '${DB_DATABASE:-accessibility_dashboard}'
            DB_USERNAME: '${DB_USERNAME:-admin}'
            DB_PASSWORD: '${DB_PASSWORD:-admin}'
            REDIS_HOST: 'redis'
            MAPBOX_ACCESS_TOKEN: '${MAPBOX_ACCESS_TOKEN:-pk.eyJ1IjoibWlsb3ZkcGFzIiwiYSI6ImNsMW5veGNtcjByaXozYnFycmdlOW1mY2gifQ.XlD67O_pB2Q-ULGzQ_HQOw}'
        volumes:
            - '.:/app'
        depends_on:
            - mysql
            - redis
        networks:
            - sail
    mysql:
        image: 'mysql:8.0.28-oracle'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE:-accessibility_dashboard}'
            MYSQL_USER: '${DB_USERNAME:-admin}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-admin}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p root"]
            retries: 3
            timeout: 5s
        networks:
            - sail
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
