# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel:
        build:
            context: ./
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:8080'
        environment:
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            DB_HOST: 'mysql'
            DB_PORT: '${FORWARD_DB_PORT:-3306}'
            DB_DATABASE: '${DB_DATABASE:-accessibility_dashboard}'
            DB_USERNAME: '${DB_USERNAME:-admin}'
            DB_PASSWORD: '${DB_PASSWORD:-admin}'
            REDIS_HOST: 'redis'
        volumes:
            - '.:/var/www/html'
        depends_on:
            - mysql
            - redis
            - selenium
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE:-accessibility_dashboard}'
            MYSQL_USER: '${DB_USERNAME:-admin}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-admin}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './mysql-data:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASE;\""]
            interval: 10s
            timeout: 2s
            retries: 10
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    selenium:
        image: 'selenium/standalone-chrome'
        volumes:
            - '/dev/shm:/dev/shm'
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
