on:
  push:
    branches:
    - main

name: Okteto Acc Deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: acc-accessibility-gewoonjaap

    - name: "Trigger the pipeline"
      uses: okteto/pipeline@latest
      with:
        namespace: acc-accessibility-gewoonjaap
        name: acc-accessibility
        variables: DB_DATABASE=accessibility_dashboard,APP_ENV=testing,DB_USERNAME=admin,DB_PASSWORD=admin,DB_HOST=mysql,MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoibWlsb3ZkcGFzIiwiYSI6ImNsMW5veGNtcjByaXozYnFycmdlOW1mY2gifQ.XlD67O_pB2Q-ULGzQ_HQOw,RADAR_SECRET=prj_test_sk_ff7db4eafcbaeab87d30a3d1b28ebae427a73372
        timeout: 8m
        skipIfExists: false
