name: Deploy Okteto Preview

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: Context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

      # Delete the Okteto Preview before deploying a new one. Fixes the issue that containers get stuck in progressing
    - name: Delete Preview
      uses: okteto/destroy-preview@latest
      with:
        name: pr-${{ github.event.number }}-gewoonjaap

      # Wait 30 seconds, to make sure the preview is destroyed. Kinda hacky lol
    - name: Waiting for preview to be deleted
      run: sleep 30s
      shell: bash

    - name: Deploy preview environment
      uses: okteto/deploy-preview@latest
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: pr-${{ github.event.number }}-gewoonjaap
        scope: personal
        timeout: 15m
        variables: DB_DATABASE=accessibility_dashboard,
                   APP_ENV=testing,DB_USERNAME=admin,
                   DB_PASSWORD=admin,DB_HOST=mysql,
                   API_KEY=${{ secrets.API_KEY }},
                   MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }},
                   RADAR_SECRET=${{ secrets.RADAR_SECRET }},
                   MAIL_USERNAME=${{ secrets.MAIL_USERNAME }},
                   MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
